// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWhVO__oDwHSXmw3qmKol82SFw7UPISvQ',
    appId: '1:92125942640:web:def6298cc72e04e8f035b5',
    messagingSenderId: '92125942640',
    projectId: 'mess-73f93',
    authDomain: 'mess-73f93.firebaseapp.com',
    storageBucket: 'mess-73f93.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqHKQMMfLfOPxPbggXNrAnaTgi9oRHdxg',
    appId: '1:92125942640:android:a98e1ebaaca55670f035b5',
    messagingSenderId: '92125942640',
    projectId: 'mess-73f93',
    storageBucket: 'mess-73f93.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBij2J58efNh3U6jgp-dj_jXaaKA5YejUw',
    appId: '1:92125942640:ios:876108e6fe58b1e7f035b5',
    messagingSenderId: '92125942640',
    projectId: 'mess-73f93',
    storageBucket: 'mess-73f93.appspot.com',
    iosClientId: '92125942640-32e4pfe58euc6329h4eqnq9vpvvq5el3.apps.googleusercontent.com',
    iosBundleId: 'com.example.mess',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBij2J58efNh3U6jgp-dj_jXaaKA5YejUw',
    appId: '1:92125942640:ios:d05f08dabecad0d9f035b5',
    messagingSenderId: '92125942640',
    projectId: 'mess-73f93',
    storageBucket: 'mess-73f93.appspot.com',
    iosClientId: '92125942640-6ltfh44i3n2siubl4jd3tghrtbb0rprg.apps.googleusercontent.com',
    iosBundleId: 'com.example.mess.RunnerTests',
  );
}
